import type { Position, Role } from "./types";

const POSITION_LABELS: Record<Position, string> = {
  GK: "Gardien",
  LB: "Arrière gauche",
  CB: "Défenseur central",
  RB: "Arrière droit",
  CDM: "Milieu défensif",
  CM: "Milieu central",
  CAM: "Milieu offensif",
  LM: "Milieu gauche",
  RM: "Milieu droit",
  LW: "Ailier gauche",
  RW: "Ailier droit",
  ST: "Avant-centre",
};

const POSITION_SHORT_LABELS: Record<Position, string> = {
  GK: "G",
  LB: "DG",
  CB: "DC",
  RB: "DD",
  CDM: "MDC",
  CM: "MC",
  CAM: "MOC",
  LM: "MG",
  RM: "MD",
  LW: "AG",
  RW: "AD",
  ST: "BU",
};

const SLOT_LABELS: Record<string, string> = {
  GK: "G",
  LB: "DG",
  LCB: "DCG",
  RCB: "DCD",
  RB: "DD",
  CDM: "MDC",
  LCM: "MCG",
  RCM: "MCD",
  LW: "AG",
  ST: "BU",
  RW: "AD",
};

const ROLE_LABELS: Record<Role, string> = {
  DEFENSIVE: "Défensif",
  NORMAL: "Équilibré",
  OFFENSIVE: "Offensif",
  CREATOR: "Créateur",
  PRESSING: "Pressing",
};

const NATIONALITY_LABELS: Record<string, string> = {
  Albania: "Albanie",
  Algeria: "Algérie",
  Andorra: "Andorre",
  "Antigua and Barbuda": "Antigua-et-Barbuda",
  Argentina: "Argentine",
  Armenia: "Arménie",
  Australia: "Australie",
  Austria: "Autriche",
  Azerbaijan: "Azerbaïdjan",
  Barbados: "Barbade",
  Belarus: "Biélorussie",
  Belgium: "Belgique",
  Benin: "Bénin",
  Bermuda: "Bermudes",
  Bolivia: "Bolivie",
  "Bosnia and Herzegovina": "Bosnie-Herzégovine",
  Brazil: "Brésil",
  Bulgaria: "Bulgarie",
  Cameroon: "Cameroun",
  "Cabo Verde": "Cap-Vert",
  "Central African Republic": "République centrafricaine",
  Chad: "Tchad",
  Chile: "Chili",
  "China PR": "Chine",
  "Chinese Taipei": "Taipei chinois",
  Colombia: "Colombie",
  Comoros: "Comores",
  "Congo DR": "RD Congo",
  Croatia: "Croatie",
  Curacao: "Curaçao",
  Cyprus: "Chypre",
  Czechia: "Tchéquie",
  Denmark: "Danemark",
  "Dominican Republic": "République dominicaine",
  Ecuador: "Équateur",
  Egypt: "Égypte",
  "El Salvador": "Salvador",
  England: "Angleterre",
  "Equatorial Guinea": "Guinée équatoriale",
  Estonia: "Estonie",
  "Faroe Islands": "Îles Féroé",
  Finland: "Finlande",
  Gambia: "Gambie",
  Georgia: "Géorgie",
  Germany: "Allemagne",
  Greece: "Grèce",
  Grenada: "Grenade",
  Guinea: "Guinée",
  "Guinea-Bissau": "Guinée-Bissau",
  Haiti: "Haïti",
  Hungary: "Hongrie",
  Iceland: "Islande",
  India: "Inde",
  Indonesia: "Indonésie",
  Iraq: "Irak",
  Ireland: "Irlande",
  "Republic of Ireland": "Irlande",
  Israel: "Israël",
  Italy: "Italie",
  Jamaica: "Jamaïque",
  Japan: "Japon",
  Jordan: "Jordanie",
  "Korea Republic": "Corée du Sud",
  Latvia: "Lettonie",
  Lebanon: "Liban",
  Liberia: "Libéria",
  Libya: "Libye",
  Lithuania: "Lituanie",
  Malaysia: "Malaisie",
  Malta: "Malte",
  Mauritania: "Mauritanie",
  Mexico: "Mexique",
  Moldova: "Moldavie",
  Montenegro: "Monténégro",
  Morocco: "Maroc",
  Namibia: "Namibie",
  Netherlands: "Pays-Bas",
  "New Caledonia": "Nouvelle-Calédonie",
  "New Zealand": "Nouvelle-Zélande",
  Nigeria: "Nigéria",
  "North Macedonia": "Macédoine du Nord",
  "Northern Ireland": "Irlande du Nord",
  Norway: "Norvège",
  Paraguay: "Paraguay",
  Peru: "Pérou",
  Philippines: "Philippines",
  Poland: "Pologne",
  "Puerto Rico": "Porto Rico",
  Romania: "Roumanie",
  Russia: "Russie",
  "Saudi Arabia": "Arabie saoudite",
  "Saint Kitts and Nevis": "Saint-Christophe-et-Niévès",
  "Saint Lucia": "Sainte-Lucie",
  Scotland: "Écosse",
  Senegal: "Sénégal",
  Serbia: "Serbie",
  Slovakia: "Slovaquie",
  Slovenia: "Slovénie",
  Somalia: "Somalie",
  "South Africa": "Afrique du Sud",
  Spain: "Espagne",
  Sweden: "Suède",
  Switzerland: "Suisse",
  Syria: "Syrie",
  Tajikistan: "Tadjikistan",
  Tanzania: "Tanzanie",
  Thailand: "Thaïlande",
  "Trinidad and Tobago": "Trinité-et-Tobago",
  Tunisia: "Tunisie",
  Türkiye: "Turquie",
  Uganda: "Ouganda",
  Ukraine: "Ukraine",
  "United Arab Emirates": "Émirats arabes unis",
  "United States": "États-Unis",
  Uzbekistan: "Ouzbékistan",
  Wales: "Pays de Galles",
  Yemen: "Yémen",
  Zambia: "Zambie",
};

export function positionLabel(position: Position | null | undefined): string {
  return position ? POSITION_LABELS[position] : "Sans poste";
}

export function positionShortLabel(position: Position | null | undefined): string {
  return position ? POSITION_SHORT_LABELS[position] : "—";
}

export function slotLabel(slotId: string): string {
  return SLOT_LABELS[slotId] ?? slotId;
}

export function roleLabel(role: Role): string {
  return ROLE_LABELS[role];
}

export function nationalityLabel(nationality: string): string {
  return NATIONALITY_LABELS[nationality] ?? nationality;
}
